# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bero_pb2 as bero__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bero_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControllerStub(object):
    """==========================================================
    1. Robot Service (로봇에서 실행, 노트북이 Client로 호출)
    노트북 -> 로봇: "주방으로 이동해", "화면 띄우고 대기해"
    ==========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Navigate = channel.unary_unary(
                '/bero.RobotController/Navigate',
                request_serializer=bero__pb2.NavigateRequest.SerializeToString,
                response_deserializer=bero__pb2.NavigateResponse.FromString,
                _registered_method=True)
        self.Deliver = channel.unary_unary(
                '/bero.RobotController/Deliver',
                request_serializer=bero__pb2.DeliverRequest.SerializeToString,
                response_deserializer=bero__pb2.DeliverResponse.FromString,
                _registered_method=True)
        self.DescribeScene = channel.unary_unary(
                '/bero.RobotController/DescribeScene',
                request_serializer=bero__pb2.SceneRequest.SerializeToString,
                response_deserializer=bero__pb2.SceneResponse.FromString,
                _registered_method=True)


class RobotControllerServicer(object):
    """==========================================================
    1. Robot Service (로봇에서 실행, 노트북이 Client로 호출)
    노트북 -> 로봇: "주방으로 이동해", "화면 띄우고 대기해"
    ==========================================================
    """

    def Navigate(self, request, context):
        """[이동 담당] 목적지로 이동하고 도착하면 성공 반환
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deliver(self, request, context):
        """[배달/대기 담당] 제자리에서 UI 띄우고 확인 누를 때까지 대기 (Blocking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeScene(self, request, context):
        """(옵션) VLM 상황 설명
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Navigate': grpc.unary_unary_rpc_method_handler(
                    servicer.Navigate,
                    request_deserializer=bero__pb2.NavigateRequest.FromString,
                    response_serializer=bero__pb2.NavigateResponse.SerializeToString,
            ),
            'Deliver': grpc.unary_unary_rpc_method_handler(
                    servicer.Deliver,
                    request_deserializer=bero__pb2.DeliverRequest.FromString,
                    response_serializer=bero__pb2.DeliverResponse.SerializeToString,
            ),
            'DescribeScene': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeScene,
                    request_deserializer=bero__pb2.SceneRequest.FromString,
                    response_serializer=bero__pb2.SceneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bero.RobotController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bero.RobotController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotController(object):
    """==========================================================
    1. Robot Service (로봇에서 실행, 노트북이 Client로 호출)
    노트북 -> 로봇: "주방으로 이동해", "화면 띄우고 대기해"
    ==========================================================
    """

    @staticmethod
    def Navigate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bero.RobotController/Navigate',
            bero__pb2.NavigateRequest.SerializeToString,
            bero__pb2.NavigateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deliver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bero.RobotController/Deliver',
            bero__pb2.DeliverRequest.SerializeToString,
            bero__pb2.DeliverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bero.RobotController/DescribeScene',
            bero__pb2.SceneRequest.SerializeToString,
            bero__pb2.SceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RobotBrainStub(object):
    """==========================================================
    2. Brain Service (노트북에서 실행, 로봇이 Client로 호출)
    로봇 -> 노트북: "나 이거 들었어(STT), 처리해줘"
    ==========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCommand = channel.unary_unary(
                '/bero.RobotBrain/ProcessCommand',
                request_serializer=bero__pb2.ChatRequest.SerializeToString,
                response_deserializer=bero__pb2.ChatResponse.FromString,
                _registered_method=True)


class RobotBrainServicer(object):
    """==========================================================
    2. Brain Service (노트북에서 실행, 로봇이 Client로 호출)
    로봇 -> 노트북: "나 이거 들었어(STT), 처리해줘"
    ==========================================================
    """

    def ProcessCommand(self, request, context):
        """로봇은 이 함수를 호출하고, 모든 처리가 끝날 때까지 대기함 (Blocking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCommand,
                    request_deserializer=bero__pb2.ChatRequest.FromString,
                    response_serializer=bero__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bero.RobotBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bero.RobotBrain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotBrain(object):
    """==========================================================
    2. Brain Service (노트북에서 실행, 로봇이 Client로 호출)
    로봇 -> 노트북: "나 이거 들었어(STT), 처리해줘"
    ==========================================================
    """

    @staticmethod
    def ProcessCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bero.RobotBrain/ProcessCommand',
            bero__pb2.ChatRequest.SerializeToString,
            bero__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
